Upload the latest binary version number to GCP  (#69)
Co-authored-by: Peter McEvoy <git@mcevoypeter.com>

diff --git a/.github/workflows/shared.yml b/.github/workflows/shared.yml
--- a/.github/workflows/shared.yml
+++ b/.github/workflows/shared.yml
@@ -185,3 +185,32 @@ jobs:
           tag="$version-${{ inputs.pace }}"
           bazel run --image_tag="$tag" :upload_docker
           bazel run --image_tag=latest :upload_docker
+
+  upload-version-string:
+    name: Upload latest deployed version string to GCP
+    runs-on: ubuntu-latest
+    needs: [urbit]
+    if: inputs.upload
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: google-github-actions/auth@v1
+        with:
+          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
+
+      - uses: google-github-actions/setup-gcloud@v1
+        with:
+          project_id: ${{ secrets.GCP_PROJECT }}
+
+      - name: Upload latest deployed version string to GCP
+        run: |
+          target="gs://${UPLOAD_BASE}/${{ inputs.pace }}/last"
+
+          # We don't use -n here because we want to overwrite the version
+          # string.
+          gsutil cp ./pkg/vere/VERSION "$target"
+
+          [ $exitcode -eq 0 ] &&
+            echo "Upload to $target completed successfully." ||
+            echo "Upload to $target failed.";
+          exit $exitcode
